name: Build and Push to GAR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and Push Docker image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-image-generator:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ai-on-gke-image-cluster --zone=us-central1-a
          sed 's/PROJECT_ID/${{ secrets.GCP_PROJECT_ID }}/g' k8s/deployment.yaml | kubectl apply -f -