name: Build, Push to GAR & Deploy to GKE

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Install gcloud SDK
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'kubectl'

      # Step 4: Configure Docker to use Artifact Registry
      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev --quiet

      # Step 5: Build and push image to GAR
      - name: Build and Push Docker image
        run: |
          IMAGE=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-image-generator/ai-image-generator:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 6: Deploy to GKE
      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ai-on-gke-image-cluster \
            --zone=us-central1-a \
            --project=${{ secrets.GCP_PROJECT_ID }}

          sed 's/PROJECT_ID/${{ secrets.GCP_PROJECT_ID }}/g' k8s/deployment.yaml \
            | kubectl apply -f -